### ISSUE TITLE
请问webpack4配置中的css的treeShaking 怎么配置

### ISSUE THREAD

**Issue by 383366204** [wlx200510/webpack4.x-learn#1]
我用PurifyCssPlugin这个插件，这样写
new PurifyCssPlugin({
    paths:glob.sync(path.join(__dirname,'../src/html/*.html')),//html模板的目录
})
但是生成出来的css把引用了的样式也删除了

**Comment by wlx200510** [comment]
引用的样式是指通过import引入的吗？是否已用postcss处理过？
把new ExtractTextPlugin 放在new PurifyCSSPlugin之前试一试

**Comment by 383366204** [comment]
似乎PurifyCSSPlugin一定要配合ExtractTextPlugin 一起使用，我用MiniCssExtractPlugin不行
