### ISSUE TITLE
dll打包时若包含@types等的包 好像会出错，似乎需要排除掉对ts环境会友好些。

### ISSUE THREAD

**Issue by iam2r** [wlx200510/webpack4.x-learn#3]
const vendor = Object.keys(pkg.dependencies).reduce((pre,cur)=>{
    !/^@types/.test(cur)?pre.push(cur):'';
    return pre;
},[])

 entry: {
        vendor
    }

**Comment by wlx200510** [comment]
这个打包确实没考虑用ts的情况，未加以测试

**Comment by wlx200510** [comment]
fixed
