### ISSUE TITLE
_dll_vendor is not defined

### ISSUE THREAD

**Issue by wangshijie0409** [wlx200510/webpack4.x-learn#4]
请问我用的react  编译成功了控制台报错  该如何解决呢？
Uncaught ReferenceError: _dll_vendor is not defined
    at eval (eval at dll-reference _dll_vendo

**Comment by wlx200510** [comment]
这说明是有些配置不对，之前也有这个问题，修改了vendor的引用配置后就好了

**Comment by wlx200510** [comment]
研究了下  可能你这块需要针对react用到的库进行dll打包优化，再进行打包操作
