### ISSUE TITLE
purifycss-webpack过滤掉有用的css

### ISSUE THREAD

**Issue by 270556660** [wlx200510/webpack4.x-learn#5]
purifycss-webpack要配合extract-text-webpack-plugin来用，在本例中npm run build会过滤掉有用的css，这要怎么解决

**Comment by wlx200510** [comment]
这个感觉是purifycss-webpack的问题，我看下怎么解决

**Comment by wlx200510** [comment]
根据purifycss-webpack 的文档，这种namespaced的css模块不支持，建议通过加个purify前缀然后在purifycss配置项上配置whiteList来解决把有用css过滤的问题
