### ISSUE TITLE
报错Error: Error: ENOENT: no such file or directory, open 'D:\worker\personal\webpackStdudy\webpack4.x-learn-master\dist\manifest.json'

### ISSUE THREAD

**Issue by zbka** [wlx200510/webpack4.x-learn#6]
Error: ENOENT: no such file or directory, open 'D:\worker\personal\webpackStdudy\webpack4.x-learn-master\dist\manifest.json'

**Comment by wlx200510** [comment]
这个应该不是框架的问题，怀疑是写入权限不够，需chmod
