### ISSUE TITLE
项目跑不起来，中间有错误

### ISSUE THREAD

**Issue by fenfeiyunluo** [wlx200510/webpack4.x-learn#7]
克隆了项目代码build的时候发现有错误，请教一下作者该怎么解决 # #

$ npm run build

> webpack4-learn@0.0.1 build C:\Users\Administrator\Desktop\webpakdemo\webpack4.                                                                       x-learn
> cross-env NODE_ENV='production' webpack --config build/webpack.prod.config.js                                                                        --mode production

clean-webpack-plugin: C:\Users\Administrator\Desktop\webpakdemo\webpack4.x-learn                                                                       \dist has been removed.
Happy[happy-babel-js]: Version: 5.0.0-beta.3. Threads: 8 (shared pool)
(node:18112) DeprecationWarning: Tapable.plugin is deprecated. Use new API on `.                                                                       hooks` instead
Happy[happy-babel-js]: All set; signaling webpack to proceed.
Error: ENOENT: no such file or directory, open 'C:\Users\Administrator\Desktop\w                                                                       ebpakdemo\webpack4.x-learn\dist\manifest.json'
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! webpack4-learn@0.0.1 build: `cross-env NODE_ENV='production' webpack --                                                                       config build/webpack.prod.config.js --mode production`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the webpack4-learn@0.0.1 build script.
npm ERR! This is probably not a problem with npm. There is likely additional log                                                                       ging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Administrator\AppData\Roaming\npm-cache\_logs\2018-09-21T0                                                                       6_23_51_784Z-debug.log

**Comment by wlx200510** [comment]
看起来有依赖包更新



发自我的小米手机
在 yaxiang <notifications@github.com>，2018年9月21日 14:26写道：

克隆了项目代码build的时候发现有错误，请教一下作者该怎么解决 # #

$ npm run build

webpack4-learn@0.0.1 build C:\Users\Administrator\Desktop\webpakdemo\webpack4. x-learn
cross-env NODE_ENV='production' webpack --config build/webpack.prod.config.js --mode production

clean-webpack-plugin: C:\Users\Administrator\Desktop\webpakdemo\webpack4.x-learn \dist has been removed.
Happy[happy-babel-js]: Version: 5.0.0-beta.3. Threads: 8 (shared pool)
(node:18112) DeprecationWarning: Tapable.plugin is deprecated. Use new API on . hooks instead
Happy[happy-babel-js]: All set; signaling webpack to proceed.
Error: ENOENT: no such file or directory, open 'C:\Users\Administrator\Desktop\w ebpakdemo\webpack4.x-learn\dist\manifest.json'
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! webpack4-learn@0.0.1 build: cross-env NODE_ENV='production' webpack -- config build/webpack.prod.config.js --mode production
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the webpack4-learn@0.0.1 build script.
npm ERR! This is probably not a problem with npm. There is likely additional log ging output above.

npm ERR! A complete log of this run can be found in:
npm ERR! C:\Users\Administrator\AppData\Roaming\npm-cache_logs\2018-09-21T0 6_23_51_784Z-debug.log

**Comment by wlx200510** [comment]
打包项目运行不能直接运行npm run build  需要先npm run dll  建议直接通过npm run prod来操作打包
