### ISSUE TITLE
请问在html中插入img标签如何实现热更新

### ISSUE THREAD

**Issue by Marslay7** [wlx200510/webpack4.x-learn#9]
添加依赖html-loader,修改HtmlWebpackPlugin插件options的属性inject为true后,
img标签指向图片能够正常显示，但是会报错：
http://localhost:1002/%3C%=%20htmlWebpackPlugin.options.vendor%20%%3E net::ERR_ABORTED 400 (Bad Request)
_dll_vendor is not defined
请问是什么原因

**Comment by wlx200510** [comment]
这个报错并非图片引起  是一个dll全局变量注入被覆盖了  导致模板编译时报错

**Comment by Marslay7** [comment]
那是添加的html-loader优先级有问题吗

**Comment by wlx200510** [comment]
这么说吧 在没有html-loader之前，是先要使用HtmlWebpackPlugin对html文件进行正则替换，替换其中的dll依赖路径，现在看起来是加入了html-loader之后把这个过程给删除了，具体还要看html-loader的配置，应该是可以解决的。

**Comment by Marslay7** [comment]
感谢回复，我再试试别的解决方案。
